src/java/jpa/entities/Wbs.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpa.entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Gibson Levvid
 */
@Entity
@Table(name = "wbs")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Wbs.findAll", query = "SELECT w FROM Wbs w"),
    @NamedQuery(name = "Wbs.findByWbsNumber", query = "SELECT w FROM Wbs w WHERE w.wbsNumber = :wbsNumber"),
    @NamedQuery(name = "Wbs.findByActive", query = "SELECT w FROM Wbs w WHERE w.active = :active"),
    @NamedQuery(name = "Wbs.findByFlagged", query = "SELECT w FROM Wbs w WHERE w.flagged = :flagged"),
    @NamedQuery(name = "Wbs.findByName", query = "SELECT w FROM Wbs w WHERE w.name = :name")})
public class Wbs implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "wbs_number")
    private String wbsNumber;
    @Basic(optional = false)
    @NotNull
    @Column(name = "active")
    private boolean active;
    @Basic(optional = false)
    @NotNull
    @Column(name = "flagged")
    private boolean flagged;
    @Size(max = 45)
    @Column(name = "name")
    private String name;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "wbs1")
    private Collection<TimeCharge> timeChargeCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "wbs")
    private Collection<WbsBreakdown> wbsBreakdownCollection;
    @JoinColumn(name = "cam", referencedColumnName = "employee_id")
    @ManyToOne
    private Employee cam;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "wbs")
    private Collection<LeaveDistribution> leaveDistributionCollection;

    public Wbs() {
    }

    public Wbs(String wbsNumber) {
        this.wbsNumber = wbsNumber;
    }

    public Wbs(String wbsNumber, boolean active, boolean flagged) {
        this.wbsNumber = wbsNumber;
        this.active = active;
        this.flagged = flagged;
    }

    public String getWbsNumber() {
        return wbsNumber;
    }

    public void setWbsNumber(String wbsNumber) {
        this.wbsNumber = wbsNumber;
    }

    public boolean getActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public boolean getFlagged() {
        return flagged;
    }

    public void setFlagged(boolean flagged) {
        this.flagged = flagged;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @XmlTransient
    public Collection<TimeCharge> getTimeChargeCollection() {
        return timeChargeCollection;
    }

    public void setTimeChargeCollection(Collection<TimeCharge> timeChargeCollection) {
        this.timeChargeCollection = timeChargeCollection;
    }

    @XmlTransient
    public Collection<WbsBreakdown> getWbsBreakdownCollection() {
        return wbsBreakdownCollection;
    }

    public void setWbsBreakdownCollection(Collection<WbsBreakdown> wbsBreakdownCollection) {
        this.wbsBreakdownCollection = wbsBreakdownCollection;
    }

    public Employee getCam() {
        return cam;
    }

    public void setCam(Employee cam) {
        this.cam = cam;
    }

    @XmlTransient
    public Collection<LeaveDistribution> getLeaveDistributionCollection() {
        return leaveDistributionCollection;
    }

    public void setLeaveDistributionCollection(Collection<LeaveDistribution> leaveDistributionCollection) {
        this.leaveDistributionCollection = leaveDistributionCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (wbsNumber != null ? wbsNumber.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Wbs)) {
            return false;
        }
        Wbs other = (Wbs) object;
        if ((this.wbsNumber == null && other.wbsNumber != null) || (this.wbsNumber != null && !this.wbsNumber.equals(other.wbsNumber))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.Wbs[ wbsNumber=" + wbsNumber + " ]";
    }
    
}

src/java/jsf/WbsController.java
package jsf;

import jpa.entities.Wbs;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.WbsFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Named("wbsController")
@SessionScoped
public class WbsController implements Serializable {

    private Wbs current;
    private DataModel items = null;
    @EJB
    private jpa.session.WbsFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    
    
    /***Custom variables**/
    private List<SelectItem> wbsList;
    @PersistenceContext
    private EntityManager em;
    
    
    
    public WbsController() {
    }

    public Wbs getSelected() {
        if (current == null) {
            current = new Wbs();
            selectedItemIndex = -1;
        }
        return current;
    }

    private WbsFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Wbs) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Wbs();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("WbsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Wbs) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("WbsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Wbs) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("WbsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Wbs getWbs(java.lang.String id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Wbs.class)
    public static class WbsControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            WbsController controller = (WbsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "wbsController");
            return controller.getWbs(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Wbs) {
                Wbs o = (Wbs) object;
                return getStringKey(o.getWbsNumber());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Wbs.class.getName());
            }
        }

    }
    
    
    /*Queries DrawingSize Table and populates drawing type ID 
    * drop down for search*/
    public List<SelectItem> getWbsNumbers() {
        wbsList = new ArrayList<SelectItem>();
        String query = "SELECT w.wbsNumber FROM Wbs w";
        List wbs_numbers;

        wbs_numbers = em.createQuery(query).getResultList();
        wbsList.add(new SelectItem(null, "WBS Number"));
        for (int i = 0; i < wbs_numbers.size(); i++) {
            wbsList.add(new SelectItem(wbs_numbers.get(i), wbs_numbers.get(i).toString()));
        }
        return wbsList;
    }

}

web/wbs/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateWbsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateWbsLabel_wbsNumber}" for="wbsNumber" />
                    <h:inputText id="wbsNumber" value="#{wbsController.selected.wbsNumber}" title="#{bundle.CreateWbsTitle_wbsNumber}" required="true" requiredMessage="#{bundle.CreateWbsRequiredMessage_wbsNumber}"/>
                    <h:outputLabel value="#{bundle.CreateWbsLabel_active}" for="active" />
                    <h:inputText id="active" value="#{wbsController.selected.active}" title="#{bundle.CreateWbsTitle_active}" required="true" requiredMessage="#{bundle.CreateWbsRequiredMessage_active}"/>
                    <h:outputLabel value="#{bundle.CreateWbsLabel_flagged}" for="flagged" />
                    <h:inputText id="flagged" value="#{wbsController.selected.flagged}" title="#{bundle.CreateWbsTitle_flagged}" required="true" requiredMessage="#{bundle.CreateWbsRequiredMessage_flagged}"/>
                    <h:outputLabel value="#{bundle.CreateWbsLabel_name}" for="name" />
                    <h:inputText id="name" value="#{wbsController.selected.name}" title="#{bundle.CreateWbsTitle_name}" />
                    <h:outputLabel value="#{bundle.CreateWbsLabel_cam}" for="cam" />
                    <h:selectOneMenu id="cam" value="#{wbsController.selected.cam}" title="#{bundle.CreateWbsTitle_cam}" >
                        <f:selectItems value="#{employeeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{wbsController.create}" value="#{bundle.CreateWbsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{wbsController.prepareList}" value="#{bundle.CreateWbsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateWbsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/wbs/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditWbsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditWbsLabel_wbsNumber}" for="wbsNumber" />
                    <h:inputText id="wbsNumber" value="#{wbsController.selected.wbsNumber}" title="#{bundle.EditWbsTitle_wbsNumber}" required="true" requiredMessage="#{bundle.EditWbsRequiredMessage_wbsNumber}"/>
                    <h:outputLabel value="#{bundle.EditWbsLabel_active}" for="active" />
                    <h:inputText id="active" value="#{wbsController.selected.active}" title="#{bundle.EditWbsTitle_active}" required="true" requiredMessage="#{bundle.EditWbsRequiredMessage_active}"/>
                    <h:outputLabel value="#{bundle.EditWbsLabel_flagged}" for="flagged" />
                    <h:inputText id="flagged" value="#{wbsController.selected.flagged}" title="#{bundle.EditWbsTitle_flagged}" required="true" requiredMessage="#{bundle.EditWbsRequiredMessage_flagged}"/>
                    <h:outputLabel value="#{bundle.EditWbsLabel_name}" for="name" />
                    <h:inputText id="name" value="#{wbsController.selected.name}" title="#{bundle.EditWbsTitle_name}" />
                    <h:outputLabel value="#{bundle.EditWbsLabel_cam}" for="cam" />
                    <h:selectOneMenu id="cam" value="#{wbsController.selected.cam}" title="#{bundle.EditWbsTitle_cam}" >
                        <f:selectItems value="#{employeeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{wbsController.update}" value="#{bundle.EditWbsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditWbsViewLink}"/>
                <br />
                <h:commandLink action="#{wbsController.prepareList}" value="#{bundle.EditWbsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditWbsIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/wbs/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListWbsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListWbsEmpty}" rendered="#{wbsController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{wbsController.items.rowCount > 0}">
                    <h:outputText value="#{wbsController.pagination.pageFirstItem + 1}..#{wbsController.pagination.pageLastItem + 1}/#{wbsController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{wbsController.previous}" value="#{bundle.Previous} #{wbsController.pagination.pageSize}" rendered="#{wbsController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{wbsController.next}" value="#{bundle.Next} #{wbsController.pagination.pageSize}" rendered="#{wbsController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{wbsController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListWbsTitle_wbsNumber}"/>
                            </f:facet>
                            <h:outputText value="#{item.wbsNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListWbsTitle_active}"/>
                            </f:facet>
                            <h:outputText value="#{item.active}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListWbsTitle_flagged}"/>
                            </f:facet>
                            <h:outputText value="#{item.flagged}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListWbsTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListWbsTitle_cam}"/>
                            </f:facet>
                            <h:outputText value="#{item.cam}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{wbsController.prepareView}" value="#{bundle.ListWbsViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{wbsController.prepareEdit}" value="#{bundle.ListWbsEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{wbsController.destroy}" value="#{bundle.ListWbsDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{wbsController.prepareCreate}" value="#{bundle.ListWbsCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListWbsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/wbs/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewWbsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewWbsLabel_wbsNumber}"/>
                    <h:outputText value="#{wbsController.selected.wbsNumber}" title="#{bundle.ViewWbsTitle_wbsNumber}"/>
                    <h:outputText value="#{bundle.ViewWbsLabel_active}"/>
                    <h:outputText value="#{wbsController.selected.active}" title="#{bundle.ViewWbsTitle_active}"/>
                    <h:outputText value="#{bundle.ViewWbsLabel_flagged}"/>
                    <h:outputText value="#{wbsController.selected.flagged}" title="#{bundle.ViewWbsTitle_flagged}"/>
                    <h:outputText value="#{bundle.ViewWbsLabel_name}"/>
                    <h:outputText value="#{wbsController.selected.name}" title="#{bundle.ViewWbsTitle_name}"/>
                    <h:outputText value="#{bundle.ViewWbsLabel_cam}"/>
                    <h:outputText value="#{wbsController.selected.cam}" title="#{bundle.ViewWbsTitle_cam}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{wbsController.destroyAndView}" value="#{bundle.ViewWbsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewWbsEditLink}"/>
                <br />
                <h:commandLink action="#{wbsController.prepareCreate}" value="#{bundle.ViewWbsCreateLink}" />
                <br />
                <h:commandLink action="#{wbsController.prepareList}" value="#{bundle.ViewWbsShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewWbsIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>